name: General Test

on:
  push:
    branches:
      - "**"

jobs:
  general:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Update ENV
        run: node fs.js
        env:
          KEY: ${{ secrets.ENCRYPTIONKEY }}
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Clone VCpkg
        run: git clone https://github.com/Microsoft/vcpkg.git
      - name: Install Via VCpkg
        run: .\vcpkg\bootstrap-vcpkg.bat
      - name: Install openssl
        run: .\vcpkg\vcpkg install openssl --triplet x64-windows-static-md
      - name: Integrate
        run: .\vcpkg\vcpkg integrate install
      - name: Build Rust
        run: cargo run --release